// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkDClg4qQfPQKfvUzdgZNGOuRMMUohjJA',
    appId: '1:723977692964:web:b9cdbe896c3a09bf0e35b1',
    messagingSenderId: '723977692964',
    projectId: 'needit-94d44',
    authDomain: 'needit-94d44.firebaseapp.com',
    storageBucket: 'needit-94d44.firebasestorage.app',
    measurementId: 'G-XXF3RPQ8JT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQBHiKT6pJhF5qtcAc2wQFplPZq_SlK7c',
    appId: '1:723977692964:android:b40549122aa77c5b0e35b1',
    messagingSenderId: '723977692964',
    projectId: 'needit-94d44',
    storageBucket: 'needit-94d44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8AotWpaU8GHpU8JBx2f6_nIe_cLdr4i0',
    appId: '1:723977692964:ios:ca4a2e0e90a212520e35b1',
    messagingSenderId: '723977692964',
    projectId: 'needit-94d44',
    storageBucket: 'needit-94d44.firebasestorage.app',
    iosBundleId: 'com.example.needitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8AotWpaU8GHpU8JBx2f6_nIe_cLdr4i0',
    appId: '1:723977692964:ios:ca4a2e0e90a212520e35b1',
    messagingSenderId: '723977692964',
    projectId: 'needit-94d44',
    storageBucket: 'needit-94d44.firebasestorage.app',
    iosBundleId: 'com.example.needitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkDClg4qQfPQKfvUzdgZNGOuRMMUohjJA',
    appId: '1:723977692964:web:9c0ab55506c6450b0e35b1',
    messagingSenderId: '723977692964',
    projectId: 'needit-94d44',
    authDomain: 'needit-94d44.firebaseapp.com',
    storageBucket: 'needit-94d44.firebasestorage.app',
    measurementId: 'G-PK6M45JE8G',
  );
}
